### ISSUE TITLE
Beta cuffs chain effects

### ISSUE THREAD

**Issue by Shylei** [NorthGlenwalker/OpenNC-Cuffs#2]
When the cuffs are chained these are long and loose when movement, apart from the thin option.  It is suggest to make the particle effects much shorter?

**Comment by NorthGlenwalker** [comment]
I Still have a lot of work to do on the chains, it has already taken me over 1 month to get them this far, it's been a much harder task then I thought to merge all the chain scripts into a single one, due to the memory usage of this script I am limited to how much functionality the system can have. BUT I will push the script to it's safe limit to include everything.

**Comment by NorthGlenwalker** [comment]
this has been fixed on 7.030 cuffs
